name: ❓ Question / Help
description: Ask a question or request help
title: "[QUESTION] "
labels: ["question", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Need help? Ask your question below. For bug reports, please use the Bug Report template instead.

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What's your question about?
      options:
        - Setup / Installation
        - Configuration
        - Architecture / Design
        - API Usage
        - Deployment
        - Contributing
        - Other
      default: 0
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Question
      description: What would you like to know?
      placeholder: How do I...? / Why does...? / What's the best way to...?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: (Optional) Provide context about what you're trying to achieve
      placeholder: |
        I'm trying to...
        My use case is...
        I've looked at...

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: (Optional) Any other relevant details
      placeholder: Environment details, code snippets, error messages, etc.
