//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

pub use super::board::Entity as Board;
pub use super::column::Entity as Column;
pub use super::task::Entity as Task;
pub use super::user::Entity as User;
