//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use utoipa::ToSchema;

#[derive(
    Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize, ToSchema,
)]
#[serde(rename_all = "camelCase")]
#[sea_orm(
    rs_type = "String",
    db_type = "Enum",
    enum_name = "board_member_role_enum"
)]
pub enum BoardMemberRoleEnum {
    #[sea_orm(string_value = "owner")]
    Owner,
    #[sea_orm(string_value = "moderator")]
    Moderator,
    #[sea_orm(string_value = "member")]
    Member,
}

impl BoardMemberRoleEnum {
    pub fn hierarchy_value(&self) -> u8 {
        match self {
            BoardMemberRoleEnum::Owner => 3,
            BoardMemberRoleEnum::Moderator => 2,
            BoardMemberRoleEnum::Member => 1,
        }
    }
}
